### ISSUE TITLE
rust_phantom_style addition

### ISSUE THREAD

**Issue by serhat359** [rust-lang/rust-enhanced#229]
### Sublime Text Version
Sublime Text 3 (Build 3126)

### Rust Enhanced Version
2.4.0

### Operating system
Windows 7 Ultimate

### The Issue
When I set `"rust_phantom_style": "none"` in settings it does not show the messages inline as it is supposed to (works with no problem), but that leaves no option to actually see the error/warning messages.

### Recommended Solution
It would be great to have a third option (as oppesed to "normal" and "none") that lets us see the errors/warnings when hovered over the outlined part of the code with the mouse (like a tooltip). I think this is the way big IDEs work (at least Eclipse and Visual Studio).

**Comment by ehuss** [comment]
Seems like a good idea.  I opened PR #230 with an implementation.  Can you check it out and give it a try and let me know what you think?

**Comment by serhat359** [comment]
Could not get it to work on my computer, nothing show up when I hover. Also the gutter images on the left appear black. Could that be related to the problem? It is possible that I messed up with my settings.

![sublime-ss](https://user-images.githubusercontent.com/10020091/33810144-72ab00d0-de12-11e7-9e5c-91c4203595ca.png)

**Comment by ehuss** [comment]
That is strange.  Did you uninstall the Package from Package Control before you cloned the git repo?  Did you try restarting Sublime?  Are there any interesting messages in the Sublime console when it starts?

**Comment by ehuss** [comment]
Just had another thought.  It might be sensitive to the name of the directory when you check it out.  Currently it should be "Rust Enhanced" with a space.  I'll push a fix in a while that fixes that.

**Comment by serhat359** [comment]
I just figured out that gutter images appearing black was because of the Color Scheme. Just to make sure, I need to hover over the outlined part of the code, right?

**Comment by ehuss** [comment]
Yea, either hover over the outline, or the gutter icon.

**Comment by Jayflux** [comment]
@serhat359 this should be fixed in the latest release https://github.com/rust-lang/rust-enhanced/releases/tag/v2.5.0

**Comment by ysimonson** [comment]
Is this working? I'm on v2.6.0, and have this in my user settings: `"rust_phantom_style": "popup",`, yet phantoms are still showing in line:

<img width="517" alt="screen shot 2018-01-25 at 4 34 51 pm" src="https://user-images.githubusercontent.com/127386/35413623-0b420ee8-01ee-11e8-8a67-abd3363e1e24.png">

**Comment by ehuss** [comment]
> Is this working?

@ysimonson It should be working.  Make sure you set `rust_phantom_style` in `RustEnhanced.sublime-settings` (not your Sublime settings).  You can open it via Preferences > Package Settings > Rust Enhanced > Settings (or the Right Mouse > Rust > ... menu).

**Comment by ysimonson** [comment]
Ah, was putting it in the wrong settings file. Thanks!
